#!/bin/bash
#SBATCH --account=fudenber_735
#SBATCH --partition=qcb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=84GB
#SBATCH --time=15:59:00
#SBATCH --array=0-10
#SBATCH --output=outputs/slurms/job_%A_%a.out

eval "$(conda shell.bash hook)"
conda activate openmm-env


export REGION="chr1:30000000-37500000"
export RUN_INDEX=${SLURM_ARRAY_TASK_ID}


echo "Running simulation with RUN_INDEX=$RUN_INDEX and REGION=$REGION"
python workflow.py

